/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as ProofPacksRouteImport } from './routes/proof-packs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProspectsIndexRouteImport } from './routes/prospects.index'
import { Route as ProspectsIdRouteImport } from './routes/prospects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofPacksRoute = ProofPacksRouteImport.update({
  id: '/proof-packs',
  path: '/proof-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIndexRoute = ProspectsIndexRouteImport.update({
  id: '/prospects/',
  path: '/prospects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIdRoute = ProspectsIdRouteImport.update({
  id: '/prospects/$id',
  path: '/prospects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/outreach': typeof OutreachRoute
  '/proof-packs': typeof ProofPacksRoute
  '/settings': typeof SettingsRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/outreach': typeof OutreachRoute
  '/proof-packs': typeof ProofPacksRoute
  '/settings': typeof SettingsRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/prospects': typeof ProspectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/outreach': typeof OutreachRoute
  '/proof-packs': typeof ProofPacksRoute
  '/settings': typeof SettingsRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/outreach'
    | '/proof-packs'
    | '/settings'
    | '/prospects/$id'
    | '/prospects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/outreach'
    | '/proof-packs'
    | '/settings'
    | '/prospects/$id'
    | '/prospects'
  id:
    | '__root__'
    | '/'
    | '/outreach'
    | '/proof-packs'
    | '/settings'
    | '/prospects/$id'
    | '/prospects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OutreachRoute: typeof OutreachRoute
  ProofPacksRoute: typeof ProofPacksRoute
  SettingsRoute: typeof SettingsRoute
  ProspectsIdRoute: typeof ProspectsIdRoute
  ProspectsIndexRoute: typeof ProspectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-packs': {
      id: '/proof-packs'
      path: '/proof-packs'
      fullPath: '/proof-packs'
      preLoaderRoute: typeof ProofPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/': {
      id: '/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof ProspectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/$id': {
      id: '/prospects/$id'
      path: '/prospects/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof ProspectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OutreachRoute: OutreachRoute,
  ProofPacksRoute: ProofPacksRoute,
  SettingsRoute: SettingsRoute,
  ProspectsIdRoute: ProspectsIdRoute,
  ProspectsIndexRoute: ProspectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
